### PR TITLE
Protect calls to execute

### LINKED ISSUE #53: Safe ETS interactions
We've seen an issue in Absinthe where a mix task is run that calls code which is instrumented with telemetry, but the handler lookup fails. The ETS table hadn't been created since telemetry wasn't started.

Given that the goal is to have telemetry embedded everywhere, should we rescue the `ArgumentError` that arises in cases like this?

https://github.com/beam-telemetry/telemetry/blob/9f009934f493719c2393adbe39eef3424411fd57/src/telemetry_handler_table.erl#L45-L47

https://github.com/absinthe-graphql/absinthe/issues/807

```
Compiling 1 file (.ex)
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:telemetry_handler_table, [:absinthe, :execute, :operation, :start])
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry_handler_table.erl:47: :telemetry_handler_table.list_for_event/1
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry.erl:114: :telemetry.execute/3
    lib/absinthe/phase/telemetry.ex:18: Absinthe.Phase.Telemetry.run/2
    lib/absinthe/pipeline.ex:366: Absinthe.Pipeline.run_phase/3
    lib/absinthe.ex:110: Absinthe.run/3
    lib/mix/tasks/compile.schema_json.ex:12: Mix.Tasks.Compile.SchemaJson.run/1
```

### PR DESCRIPTION
**Pull request by binaryseed**
This PR wraps the calls to `telemetry:execute` to protect against crashes if the `telemetry` app hasn't started & the ETS tables don't exist.

I haven't written much erlang so all feedback is welcome

fixes #53

### CODE REVIEW

File: test/telemetry_SUITE.erl [hunk 1]
```diff
@@ -27,6 +28,12 @@ end_per_testcase(_, Config) ->
     HandlerId = ?config(id, Config),
     telemetry:detach(HandlerId).
 
+% Ensure calling execute is safe even if telemetry app isn't running
+safe_execute(Config) ->
```
Comment (josevalim) [inline test/telemetry_SUITE.erl]: I would rather call it "unsafe_execute" or "off_execute", as it is not inherently safe, but we are making it be. :)

File: src/telemetry_handler_table.erl [hunk 2]
```diff
@@ -44,7 +44,14 @@ delete(HandlerId) ->
 
 -spec list_for_event(telemetry:event_name()) -> [#handler{}].
 list_for_event(EventName) ->
-    ets:lookup(?MODULE, EventName).
+    try
+        ets:lookup(?MODULE, EventName)
+    catch
+        error:badarg ->
+            error_logger:warning_msg("Failed to lookup telemetry handlers. "
```
Comment (josevalim) [inline src/telemetry_handler_table.erl]: There are some macros in `telemetry.erl`. We should move them to `telemetry.hrl` and use them here. The advantage of using the macros is that we don't even need to make the mode configurable, people can just use logger APIs if they want to silence the warning. :)

Comment (binaryseed) [reply src/telemetry_handler_table.erl]: will do - how would someone silence them?

Comment (josevalim) [reply src/telemetry_handler_table.erl]: They can use: http://erlang.org/doc/man/logger.html#set_application_level-2

    :logger.set_application_level(:telemetry, :none)

**Comment by josevalim** [comment]
@arkgil anything to add? :D

**Comment by arkgil** [comment]
Looks great, thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@arkgil when you have some time, can you please ship v0.4.1? The last time I shipped the released was borked (iirc).

**Comment by arkgil** [comment]
@josevalim sure thing!

File: src/telemetry_handler_table.erl (hunk 2 above)
Comment (binaryseed) [reply src/telemetry_handler_table.erl]: That's sweet!

Does the Elixir `Logger` gain this feature with 1.10 ?

**Comment by binaryseed** [comment]
Awesome!!

File: src/telemetry_handler_table.erl (hunk 2 above)
Comment (josevalim) [reply src/telemetry_handler_table.erl]: Yes it does!
